name: PluginManager
main: pl.PluginManager.Main
version: 0.0.1
authors: [DragoPL/eX., UssCompany]
description: Plugins managing!
commands:
  pluginmanager:
    aliases: [pluginman, plgmanager, manager]
    description: PluginManager Command.
permissions:
  pluginon:
    description: Allows you to use the /pluginmanager on command
  pluginoff:
    description: Allows you to use the /pluginmanager off command