name: PluginManager
main: pl.PluginManager.Main
version: 0.0.1
authors: [DragoPL/eX., UssCompany]
description: Plugins managing!
commands:
    pluginmanager:
        aliases: [pluginman, plgmanager, manager]
        description: PluginManager Command.
permissions:
    pluginmanager.enable:
        description: Allows you to use the /pluginmanager enable command
    pluginmanager.disable:
        description: Allows you to use the /pluginmanager disable command
    pluginmanager.reload:
        descroption: Allow you to use the /pluginmaneger reload command
    pluginmanager.*:
        description: Allows you to use all plugin's commands
